### PR TITLE
Fix PReLU bug

### LINKED ISSUE #179: PReLU conversion in caffe parser
Hi, 

I have found that the implementation of PReLU conversion in the Caffe parser isn't correct.
The issue goes from here when **channelShared==false**:
https://github.com/NVIDIA/TensorRT/blob/466657173a93d72ab07942cf6b634a92986fa922/parsers/caffe/caffeParser/opParsers/parsePReLU.cpp#L40
Apparently, **slopesDims** should look like this (C, 1, 1) in the 2-d case and (C, 1) in the 1-d case. In your implementation, it looks like (1, H, 0) in the 2-d case which is completely incorrect and leads to some errors because one of the dimensions is 0 or (1, H) in the 1-d case which seems to be incorrect as well.

### PR DESCRIPTION
**Pull request by yqbeyond**
Fix #179
Fix the bug when parse PReLU layer in caffe parser.

### CODE REVIEW

**Comment by kostinalexey** [comment]
This fix is not fully correct. It does not deal with the case when inputDims.nbDims == 4. For example this is the case when network is created with 
```
builder->createNetworkV2(1U << static_cast<uint32_t>(NetworkDefinitionCreationFlag::kEXPLICIT_BATCH))
```
Where the first dimension is kINDEX (batch size)

**Comment by rmccorm4** [comment]
> For example this is the case when network is created with kEXPLICIT_BATCH

I don't believe the Caffe parser supports explicit batch, so I'm not sure that specific case would be an issue.

**Comment by 121786404** [comment]
error parsing layer type PReLU index 21
Segmentation fault (core dumped)

**Comment by kostinalexey** [comment]
I just had a time to experiment more with this issue and I can make TensorRT work with the fix I proposed in #355 and explicit batch. Numerically results close (diff<1e-6) to ones from caffe.

**Comment by twmht** [comment]
got verified and it works

**Pull request closed without merging**
