### PR TITLE
Add multiple ControlNet support to demoDiffusion

### PR DESCRIPTION
**Pull request by keddyjin**
Add multiple ControlNet support to demoDiffusion, implemented the text2img pipeline, with some performance data

### CODE REVIEW

**Review by snlpatel001213 — COMMENTED** [review]
#Error
```
root@21711ed6b1e1:/workspace/demo/Diffusion# python3 demo_txt2img_controlnet.py "a beautiful photograph of Mt. Fuji during cherry blossom" -v
/usr/local/lib/python3.8/dist-packages/controlnet_aux/mediapipe_face/mediapipe_face_common.py:7: UserWarning: The module 'mediapipe' is not installed. The package will have limited functionality. Please install it using the command: pip install 'mediapipe'
  warnings.warn(
[I] Initializing StableDiffusion [Controlnet] txt2img demo using TensorRT
[I] StableDiffusion without controlnet
Exporting model: onnx/unet.onnx
/usr/local/lib/python3.8/dist-packages/diffusers/models/unet_2d_condition.py:526: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if any(s % default_overall_up_factor != 0 for s in sample.shape[-2:]):
/usr/local/lib/python3.8/dist-packages/diffusers/models/resnet.py:185: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert hidden_states.shape[1] == self.channels
/usr/local/lib/python3.8/dist-packages/diffusers/models/resnet.py:190: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert hidden_states.shape[1] == self.channels
/usr/local/lib/python3.8/dist-packages/diffusers/models/resnet.py:112: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert hidden_states.shape[1] == self.channels
/usr/local/lib/python3.8/dist-packages/diffusers/models/resnet.py:125: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if hidden_states.shape[0] >= 64:
/usr/local/lib/python3.8/dist-packages/diffusers/models/unet_2d_condition.py:651: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if not return_dict:
============= Diagnostic Run torch.onnx.export version 2.0.1+cu117 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 1 ERROR ========================
ERROR: missing-standard-symbolic-function
=========================================
Exporting the operator 'aten::scaled_dot_product_attention' to ONNX opset version 17 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.
```

**Comment by azhurkevich** [comment]
@snlpatel001213 this is PyT 2.0 bug, downgrade to 1.14 or 23.02 nvcr image and it'll work

**Comment by keddyjin** [comment]
I've updated the installation instructions, it should work now on both nvcr.io/nvidia/pytorch:23.02-py3, nvcr.io/nvidia/pytorch:23.04-py3 and other pytorch images above 23.02

**Comment by snlpatel001213** [comment]
I will check and add review

**Comment by rajeevsrao** [comment]
Synced up with @keddyjin internally. ControlNet support in demoDiffusion will be released with TRT/9.0.

**Comment by LucasMoskun** [comment]
When using the tensorrt version of controlnets are you able to change the conditional image? Or is the .engine tied to the conditional image supplied at time of conversion?

**Pull request closed without merging**
