### PR TITLE
Add FP16 support to batchedNMSPlugin

### PR DESCRIPTION
**Pull request by pbridger**
Add support for float16 boxes and scores (but not mixed precision between boxes and scores).

Gives inference results within expected numerical tolerances using SSD300 and COCO2017 validation set. (As detailed here https://paulbridger.com/posts/tensorrt-object-detection-quantized/).

Despite the "#if __CUDA_ARCH__ >= 800" this has not been tested on Ampere, only Turing arch.

### CODE REVIEW

**Comment by rajeevsrao** [comment]
Thanks @pbridger. Can you please sign your commits with `git commit --amend -s`

**Comment by pranavm-nvidia** [comment]
@rajeevsrao Does this need to be integrated into master as well?

**Comment by rajeevsrao** [comment]
> @rajeevsrao Does this need to be integrated into master as well?

Yes, but we will cherry-pick it internally first, test and release to master via 21.0x and then merge this change.

**Review by pranavm-nvidia — APPROVED** [review]

**Review by rajeevsrao — APPROVED** [review]

**Comment by rajeevsrao** [comment]
Thanks @pbridger. Will merge this commit once the corresponding cherry-pick for master is posted alongwith the 21.02 container update.

**Comment by pbridger** [comment]
Cool! Many thanks @rajeevsrao and @pranavm-nvidia for all your work to include this.

**Pull request merged**
