### PR TITLE
[onnx graphsurgeon]add type for Variable

### PR DESCRIPTION
**Pull request by inisis**
https://github.com/NVIDIA/TensorRT/issues/3304

### CODE REVIEW

**Comment by inisis** [comment]
@rajeevsrao Hi, can this be merged.

**Comment by rajeevsrao** [comment]
@yuanyao-nv will followup once we integrate the change internally.

**Comment by inisis** [comment]
> @yuanyao-nv will followup once we integrate the change internally.

@rajeevsrao so my pr has to be closed once this change was integrated by you, right? I want to be your contributor.

**Comment by rajeevsrao** [comment]
> > @yuanyao-nv will followup once we integrate the change internally.
> 
> @rajeevsrao so my pr has to be closed once this change was integrated by you, right? I want to be your contributor.

@inisis yes, once we verify the change doesn't break any of our tests, we will merge it on our internal repo first and then your PR here. Thanks for your contribution!

**Comment by yuanyao-nv** [comment]
This commit has been cherry-picked internally. We can merge this PR now.

**Pull request merged**
