### PR TITLE
TensorRT OSS 9.1.0 Release

### PR DESCRIPTION
**Pull request by SimengLiu-nv**

### CODE REVIEW

**Review by nvpohanh — APPROVED** [review]

**Comment by oscarbg** [comment]
Hi,
sorry for asking directly here, but can also include the TensorRT 9.1 GA Windows download links also in this PR?

I see:

> Else download and extract the TensorRT GA build from [NVIDIA Developer Zone](https://developer.nvidia.com) with the direct links below:
>  [TensorRT 9.1.0.4 for CUDA 12.2, Linux x86_64](https://developer.nvidia.com/downloads/compute/machine-learning/tensorrt/secure/9.1.0/tars/tensorrt-9.1.0.4.linux.x86_64-gnu.cuda-12.2.tar.gz)

but missing Windows download links which are needed for TensorRT-LLM for Windows as seen in this guide:
https://github.com/NVIDIA/TensorRT-LLM/tree/release/0.5.0/windows

thanks..

**Comment by rajeevsrao** [comment]
> Hi, sorry for asking directly here, but can also include the TensorRT 9.1 GA Windows download links also in this PR?
> 
> I see:
> 
> > Else download and extract the TensorRT GA build from [NVIDIA Developer Zone](https://developer.nvidia.com) with the direct links below:
> > [TensorRT 9.1.0.4 for CUDA 12.2, Linux x86_64](https://developer.nvidia.com/downloads/compute/machine-learning/tensorrt/secure/9.1.0/tars/tensorrt-9.1.0.4.linux.x86_64-gnu.cuda-12.2.tar.gz)
> 
> but missing Windows download links which are needed for TensorRT-LLM for Windows as seen in this guide: https://github.com/NVIDIA/TensorRT-LLM/tree/release/0.5.0/windows EDIT: TensorRT-LLM Windows guide instructions:
> 
> ```
> [cuDNN and TensorRT](https://github.com/NVIDIA/TensorRT-LLM/tree/release/0.5.0/windows#cudnn-and-tensorrt)
> Download and unzip [TensorRT 9.1.0.4](https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html#installing-zip).
> ```
> 
> thanks..

@oscarbg Thanks for your comment. For the TensorRT-OSS 9.x releases, Windows is not an officially supported target and are only meant to support TRT-LLM.

**Comment by ddelange** [comment]
Hi 👋

When is the [PyPI](https://pypi.org/project/tensorrt/) release for tensorrt 9.1.0 planned?

**Comment by SimengLiu-nv** [comment]
> Hi 👋
> 
> When is the [PyPI](https://pypi.org/project/tensorrt/) release for tensorrt 9.1.0 planned?

@ddelange Thank you for your comment. Since the current release has limited supporting target and not "official", we do not plan to release a python build to PyPI. You can install the developer build using `pip3 install --pre --extra-index-url https://pypi.nvidia.com/ tensorrt` (for cuda-12).

**Pull request merged**
