### PR TITLE
[FIX] Function Name Mismatch in trtexec:tracer.py

### PR DESCRIPTION
**Pull request by CryptoSalamander**
when I run 
`$ python3 tracer.py trace.json` like in trtexec's readme file.

I encountered an error like below:

`Traceback (most recent call last):
  File "tracer.py", line 48, in <module>
    metricsDescription = pu.combine_descriptions('Possible metrics (all in ms) are:',
AttributeError: module 'prn_utils' has no attribute 'combine_descriptions'`

this error caused by mismatching function name.
prn_util's function name was 'combineDescriptions'
so I changed it 'combine_descriptions'

after this process, 
tracer.py works well.

### CODE REVIEW

**Comment by CryptoSalamander** [comment]
@rajeevsrao Hi! I solved a very simple issue, function name mismatching in trtexec's tracer.py.
Guess this mismatching was caused by the change of function name coding invention.
Could you please check this PR?

**Comment by rajeevsrao** [comment]
@CryptoSalamander please sign your commit `git commit --amend -s`

**Comment by CryptoSalamander** [comment]
> @CryptoSalamander please sign your commit `git commit --amend -s`
Thanks for your reply.
I Signed it.

**Comment by rajeevsrao** [comment]
@CryptoSalamander profiler.py and `prn_utils.py` use `combineDescriptions` while `tracer.py` uses `combine_descriptions`. Can you instead update `tracer,py`?

**Review by rajeevsrao — CHANGES_REQUESTED** [review]
Please update `tracer.py` to `combineDescriptions` instead.

**Comment by CryptoSalamander** [comment]
@rajeevsrao 
Okay, I changed tracer.py and restore prn_utils.

**Review by rajeevsrao — APPROVED** [review]

**Comment by CryptoSalamander** [comment]
@rajeevsrao Thank you for your approval! 
would it be possible to merge?

**Pull request merged**
