### PR TITLE
Enforce ONNX Checker and Shape Inference Whenever Needed for Examples

### PR DESCRIPTION
**Pull request by leimao**
* Add ONNX checker whenever possible.
* Add shape inference to complete the output tensor shape for some ONNX models.

### CODE REVIEW

**Review by pranavm-nvidia — DISMISSED** [review]

**Comment by leimao** [comment]
@rajeevsrao

**Comment by leimao** [comment]
@rajeevsrao I applied the diff patch from @pranavm-nvidia. However, there is a conflict between this patch and the `NVIDIA:release/8.5` patch which is also ahead of the `main`. Do I need to rebase my patch on top of `NVIDIA:release/8.5`? I believe Pranav used the `main` instead of the `NVIDIA:release/8.5` as his base.

**Comment by leimao** [comment]
Oh wait, I was not merging to the `main`. Let me check if I can correct the branch for merging.

**Comment by leimao** [comment]
GitHub does not allow changing the merging branch in an MR. Creating a new on in #2619. Closing this one.

**Pull request closed without merging**
