### PR TITLE
onnx-graphsurgeon - fix node domain bug

### PR DESCRIPTION
**Pull request by inisis**
In onnx. node domain is very important, but onnx-graphsurgeon will ignore it, this pr will fix this bug.

### CODE REVIEW

**Comment by inisis** [comment]
@rajeevsrao @SimengLiu-nv @ttyio Can this be merged?

**Comment by rajeevsrao** [comment]
@pranavm-nvidia please review.

@inisis can you please signoff on your commit?
https://github.com/NVIDIA/TensorRT/blob/main/CONTRIBUTING.md#signing-your-work

**Review by pranavm-nvidia — COMMENTED** [review]
Can you add an entry to the CHANGELOG too?

**Review by pranavm-nvidia — APPROVED** [review]

**Comment by inisis** [comment]
@pranavm-nvidia CHANGELOG updated.

**Review by rajeevsrao — APPROVED** [review]

**Comment by inisis** [comment]
@rajeevsrao Hi, it seems that workflow is blocked, is there anything that I can do with that.

**Comment by rajeevsrao** [comment]
> @rajeevsrao Hi, it seems that workflow is blocked, is there anything that I can do with that.

Merged. Thanks for contributing.

**Pull request merged**
