### PR TITLE
Update batchedNMSPlugin to support dynamic batch size

### PR DESCRIPTION
**Pull request by zldrobit**
*Update batchedNMSPlugin to support dynamic batch  size*
Address #544 

To support dynamic batch size, change parent class of batchedNMSPlugin from IPluginV2Ext to IPluginV2DynamicExt.

Signed-off-by: Jiacong Fang <zldrobit@126.com>

### CODE REVIEW

**Comment by zldrobit** [comment]
Hi @rmccorm4, please help me to review this PR to avoid potenial bugs.
We are using this modified plugin with TRTIS in a high-throughput inference scenario.
With this modified plugin, our GPU ultilization rise from 60-70% to 90%+.
Another user also found this PR useful (https://github.com/NVIDIA/TensorRT/issues/523#issuecomment-649071522).
If BatchedNMSPlugin supports dynamic batch size, throughput of object detection will increase on TensorRT inference.

**Comment by rajeevsrao** [comment]
@zldrobit Thanks for your PR! There was a parallel PR containing the same change which have verified internally. See https://github.com/NVIDIA/TensorRT/pull/704/commits/0e1638dac2f5cf2b7c709163729ff4566db44c90

**Comment by zldrobit** [comment]
Thanks for your acknowledgement, but it is strange since @rmccorm4 encouraged me to send a PR two months ago (https://github.com/NVIDIA/TensorRT/issues/544#issuecomment-628727748).
During the last two months, there seems no PR to address [this issue](https://github.com/NVIDIA/TensorRT/issues/544). 
As a result, I could only commit this PR before the release of TensorRT v7.1 to help others to use dynamic input feature with batchedNMSPlugin.
Anyway, I hope this PR could be helpful.

**Comment by rajeevsrao** [comment]
@zldrobit I take the blame for not following up on the PR. When I tried it on yolo it was segfaulted so went with the internal version. Will followup on PRs more proactively going forward, and we certainly value your contributions.

**Pull request closed without merging**
